# Generated by Django 4.1.9 on 2023-08-24 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_game_gameaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameaction',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_actions', to='core.game'),
        ),
    ]
